### PR TITLE
feat: refactor 'nix develop' flake

### PR DESCRIPTION
**Pull request by hlolli**
using the legacy nixpkgs caused an issue on my aarch64-darwin system, as it tried to execute linux binaries, therefore I pass the system variable into the import of nixpkgs, and the issue is gone.

### CODE REVIEW

**Review by djwhitt — CHANGES_REQUESTED** [review]
Change itself looks fine, but I have two requests for the commit message:

- Switch it from `feat:` to `refactor:`
- Include the PR description in the body of the commit

I want to make sure we have a commit history that provide enough info for people to fairly easily make sense of our changes in the future.

**Comment by djwhitt** [comment]
Force pushing to the branch is fine to update the commit message.

**Comment by djwhitt** [comment]
I probably should expand slightly for clarity:

I overall don't care that much about conventional commit style, but I think it makes sense to be somewhat strict about `feat` and `fix` usage since those are useful for constructing change logs and release notes. That's a relatively minor consideration though, the thing that is much more important to me is explaining why changes are made somewhere in the commit message. It helps so much when trying to make sense of the history later. In OSS projects that's especially important. Of course, there are exceptions (e.g. a series of related refactoring might not need to re-explain the rationale for each change), but those should be rare.

**Comment by hlolli** [comment]
wait let me remove those leading whitespaces in my commit message....

**Comment by djwhitt** [comment]
@hlolli Looks good. Appreciate it! :pray:

Rebased and merged into `develop`.

**Pull request closed without merging**
